Adding page - How to obtain LEth (Lisinski Ethereum)
hpoa/community pull request #1
Opened 2019-03-04 22:45 UTC by edisinovcic

2019-03-05 05:38 UTC, Swader requested changes
Super, thx, samo napraviš ove manje ispravke i šibamo

2019-03-05 05:38 UTC, Swader commented on authors/edisinovcic/obtain-LEth/hr_HR/final.md
> +# How to obtain LEth (Lisinski Ethereum)
višak

2019-03-05 05:38 UTC, Swader commented on authors/edisinovcic/obtain-LEth/hr_HR/final.md
> +Ukoliko je sve bilo uspješno vidit ćete obavijest.
~vidit~ vidjeti

2019-03-05 05:38 UTC, Swader commented on authors/edisinovcic/obtain-LEth/hr_HR/final.md
> +Sada bi vaš wallet trebao biti bogatiji za 0.5 LEth-a.
~wallet~ novčanik, i novčanik linkati na https://bitfalls.com/hr/2017/08/31/what-cryptocurrency-wallet/

2019-03-05 05:38 UTC, Swader commented on authors/edisinovcic/obtain-LEth/en_US/final.md
> +Once there copy your wallet address and click on I'm not a robot.
Navodnici oko "I'm not a robot"

2019-03-05 05:38 UTC, Swader commented on authors/edisinovcic/obtain-LEth/en_US/final.md
> +Once you succeed you will see below image.
the below image

2019-03-05 05:38 UTC, Swader commented on authors/edisinovcic/obtain-LEth/en_US/final.md
> +Your wallet balance should now be updated.
Wallet linkat na https://bitfalls.com/2017/08/31/what-cryptocurrency-wallet/

2019-03-05 09:23 UTC, edisinovcic commented
Ostalo je fixano, pogledaj samo da je markdown za linkove dobro napravljen.

2019-03-05 11:16 UTC, merged

2019-03-05 11:17 UTC, Swader commented
@edisinovcic super, thanks! Možeš ih bacit u forum kao nove postove, slike onda linkaš odavde - znači na raw sliku s githuba. Ja onda apdejtam originalne postove s linkovima na tvoje nove.

2019-03-07 18:00 UTC, edisinovcic commented
Dodano: https://forum.lisinski.online/d/7-raw-images

2019-03-07 18:43 UTC, Swader commented
Mmm krivo sam objasnio. Postove dodaš na forum. A na images linkaš na github, tako da ih ne uploadaš na forum (jer ne možeš).

2019-03-08 09:45 UTC, edisinovcic commented
Smotan san, al ne mogu nać tag koji ide, jel imaš negdi dokumentaciju za forum? :) 

Koji se sve tagovi mogu koristit? :)

https://forum.lisinski.online/d/8-how-to-obtain-leth-lisinski-ethereum